# cPanel YAML file for deploying a Create React App project

deployment:
  tasks:
    - name: Install dependencies
      command: npm install
    - name: Build the React app
      command: npm run build
    - name: Move build to deployment directory
      command: mv build/* /home/your-cpanel-username/public_html/
